### ISSUE TITLE
Redirect to sign in when clicking join game and not signed in

### ISSUE THREAD

**Issue by edgarrambo** [Coding-Knights/chess#62]
when you are not signed in, and click join game you get an error page.

We need to code it to that it redirects to a sign up page if not signed in.

**Comment by jaykibi** [comment]
gotcha, we would need to make it so the user is redirected to the log in page on clicking the join game button.

**Comment by edgarrambo** [comment]
This one has been fixed

**Comment by edgarrambo** [comment]
just need to add a logged in user code.

**Comment by edgarrambo** [comment]
fixed
